let name = "Али";        // Студенттің аты
let age = 25;            // Студенттің жасы
let isStudent = true;    // Студент статусын білдіреді


console.log("Аты: " + name + " | Типі: " + typeof name);
console.log("Жасы: " + age + " | Типі: " + typeof age);
console.log("Студент пе?: " + isStudent + " | Типі: " + typeof isStudent);


age = age.toString(); 


console.log("Жасы (жол ретінде): " + age + " | Типі: " + typeof age);
